require 'spec_helper'

# https://www.youtube.com/watch?v=7QEp1UbP4GA
# see also: https://habr.com/ru/post/195048/
context 'Vagrant Ansible Plugin support files' do
  context 'Ansible inventory generated by Vagrant' do
    # ansible at a minimum requires playbook and inventory.  
    # The playbook provided explicitly, and inventory is pauto-generated by Vagrant plugin
    # this allows running the ansible playbook from host targeting the node via
    # ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory playbook.yml
    # NOTE: in [multi-machine mode](https://www.vagrantup.com/docs/multi-machine) 
    # Vagrant seems to miss grouping the machines
    mountdir = '/vagrant'
    inventory_path = '.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory'
    describe file "#{mountdir}/#{inventory_path}" do
      it { should be_file }
      {
        'ansible_host' => '127.0.0.1',
        'ansible_port' => '2222',
        'ansible_user' => "'vagrant'",  
        'ansible_ssh_private_key_file' => '.*.vagrant/machines/default/virtualbox/private_key',
      }.each do |key,value_matcher|
        its(:content) { should match /#{key}=#{value_matcher}/ }
      end
    end
  end
end
